### ISSUE TITLE
Observation Token issue

### ISSUE THREAD

**Issue by zaki850** [scrubbless/PublishedScenarios#9]
![image](https://user-images.githubusercontent.com/26735015/35351806-5f650e32-0142-11e8-9b2a-28fd339cbd2c.png)

The observation token is only to the bottom of the tile and forces you to go that way and only after you discover the beach and the alley next to the bookshop, despite the fact that after discovering them you can move to those areas from the boat pier. I understand you did not want the investigators to uncover such a large map area straight away but it still was a bit weird that such a big area could not be seen while standing next to it. Maybe it can be solved by some absence of light there on the street?

**Comment by scrubbless** [comment]
This was was tricky for me. The major easy to attain clue is on Berth 3, and missing it would cause a lot of walking. So I opted to path the player round there. If I could, I would have blocked access from the rental dock to the street. However you can't lay non tiles down and putting an explore token with dialog would have just look pants.

In version 2, I have removed the entire "East Alley" and "North Street" (including the beach). So will be adding an explore to the plaza behind the rental office. Simply because the map is smaller and it would not be the end of the world to run back to Berth 3 to pick up the clue.

![image](https://user-images.githubusercontent.com/32058089/35381460-4297c9d0-01b4-11e8-87e0-99b2f3f61002.png)

I am curious as to your opinion on this, its quite a bold move and I am worried it will take away some of the Grandiose nature of the "town" of Ambersby.

It does however (with some tweaks) only require Base and MoM1E.

**Comment by zaki850** [comment]
I liked the map layout and indeed it made the town feel more like a real town thanks to the streets. The distance wasn't a problem as well thanks to the shortcut after breaking the window in the cellar (we split - 1 investigator went to the Sheriff, the other to East street), but it's up to you. This one looks good as well.

**Comment by scrubbless** [comment]
One of the comments from my play tests, was that there were a lot of "move 4 spaces" actions. Which feel a bit lacklustre in my experience. That is why I added the shortcut in the Holding Cell, originally there was only one in the warehouse.

Also the game felt very long, early game being very slow paced as you wandered the streets not doing much, then the end slamming you with a plot stick, room after room. 

In our first game, we couldn't kill the monsters and I had not capped the monsters that spawned from corpses (not sure if you triggered any). Suffice to say we ran for the boat with 5 monsters and the big bad chasing us!

Did you trigger any monsters from corpses or see the "helper" random event?

**Comment by zaki850** [comment]
Yeah I had both - I think even 2 monsters from corpses plus the "helper"
event (the little girl in the shack - great idea by the way).  However, I
found the rifle with 5 attack at the beginning (character with 5 strength &
5 agility after using improvement)  + I had a character from Streets of
Arkham - the one that can cast a spell for free before her round and she
had the 5 attack spell, so the monsters were going down after one attack.
Both investigators were a bit overpowered in combat but we still barely won
- maybe in a different team this would have been too hard, now that I think
about it.

**Comment by scrubbless** [comment]
My gaming group had a similar play test with the new investigators, they are OP.

The cure ending is not meant to be easy, I have intentionally paced it so that a party picking up all clues (without a single skill failure or missed attack) can get to the end just as the final boss spawns. The idea being, if people are held up, they should be expected to skip obvious "filler" tokens to get to the end game. There are enough clues to send them to the Sheriff's office, early in the game. 

However, the replay-ability of the game is hindered by the final puzzle. Once you know the colour sequence you know it, on a second play you could skip clues and just punch in the order.

I would ideally like to randomise the serum ingredient colours, but I think it would be quite hard to code. 

The idea being I could roll a random variable:

VialCombination = #rand3 

That would generate an order.
I could then add additional events (and prevent current events from ) spawning clues. The idea being order one would be the one you played. Order 2 would not place the berth note, instead have the clue on the man in the plaza, or have the test subject in the house not appearing (or even him being dead instead, and giving a clue to another colour).
Then i'd just need events on the apparatus that expect a different sequence order.

I could extrapolate that out as many times as I like, maybe even adding combinations in that use different expansions.

Hmmm... maybe version 3 :D

**Comment by scrubbless** [comment]
> However, I
found the rifle with 5 attack at the beginning

That was intentional. You get the carbine rifle, shotgun or tommy gun from that cabinet.

The wrack spell was pure luck. First few times I played, i didn't realise that spell was a melee spell, can imagine its annoying to have with the SoA spell caster character.
